# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Comment',
			fields=[
				('comment_id', models.AutoField(primary_key=True, serialize=False)),
				('text', models.CharField(max_length=500)),
				('created', models.DateTimeField(auto_now_add=True)),
				('updated', models.DateTimeField(auto_now=True)),
			],
			options={
				'db_table': 'comment_tab',
			},
		),
		migrations.CreateModel(
			name='Event',
			fields=[
				('event_id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=200)),
				('description', models.CharField(max_length=500)),
				('tags', models.CharField(max_length=200)),
				('start', models.DateTimeField()),
				('end', models.DateTimeField()),
				('created', models.DateTimeField(auto_now_add=True)),
				('updated', models.DateTimeField(auto_now=True)),
			],
			options={
				'db_table': 'event_tab',
			},
		),
		migrations.CreateModel(
			name='Image',
			fields=[
				('image_id', models.AutoField(primary_key=True, serialize=False)),
				('image_path', models.CharField(max_length=400)),
				('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event')),
			],
			options={
				'db_table': 'image_tab',
			},
		),
		migrations.CreateModel(
			name='Like',
			fields=[
				('like_id', models.AutoField(primary_key=True, serialize=False)),
				('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event')),
			],
			options={
				'db_table': 'like_tab',
			},
		),
		migrations.CreateModel(
			name='Participation',
			fields=[
				('participation_id', models.AutoField(primary_key=True, serialize=False)),
				('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event')),
			],
			options={
				'db_table': 'participation_tab',
			},
		),
		migrations.CreateModel(
			name='User',
			fields=[
				('user_id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=200)),
				('username', models.CharField(max_length=32)),
				('passhash', models.CharField(max_length=70)),
				('salt', models.CharField(max_length=32)),
				('admin', models.BooleanField()),
				('created', models.DateTimeField(auto_now_add=True)),
				('updated', models.DateTimeField(auto_now=True)),
			],
			options={
				'db_table': 'user_tab',
			},
		),
		migrations.AddField(
			model_name='participation',
			name='user',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.User'),
		),
		migrations.AddField(
			model_name='like',
			name='user',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.User'),
		),
		migrations.AddField(
			model_name='comment',
			name='event',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event'),
		),
		migrations.AddField(
			model_name='comment',
			name='user',
			field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.User'),
		),
	]
