# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('eventapp', '0002_auto_20180605_0335'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='username',
			field=models.CharField(db_index=True, max_length=64),
		),
	]
